#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# index:
#    path: /
#    controller: App\Controller\HelloController::sayHello
index:
   path: /
   controller: App\Controller\AuthorController::index
